# Generated by Django 4.2 on 2023-04-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="authors",
            field=models.ManyToManyField(to="posts.author"),
        ),
    ]
