# Generated by Django 4.2 on 2023-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_website_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "name",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("color", models.CharField(max_length=40)),
            ],
        ),
    ]
