# Generated by Django 4.2 on 2023-04-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_car"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="color",),
        migrations.AddField(
            model_name="user",
            name="cars",
            field=models.ManyToManyField(to="users.car", verbose_name="user's cars"),
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="user's name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="user's last name"),
        ),
        migrations.AlterField(
            model_name="website", name="url", field=models.URLField(unique=True),
        ),
    ]
